services:
    stevotvr.steamstatus.controller:
        class: stevotvr\steamstatus\controller\main
        arguments:
            - '@config'
            - '@request'
            - '@cache'
            - '@language'
    stevotvr.steamstatus.listener:
        class: stevotvr\steamstatus\event\main_listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'
            - '@request'
            - '@user'
            - '@dbal.conn'
        tags:
            - { name: event.listener }
