parameters:
    stevotvr.steamstatus.tables.steamstatus: '%core.table_prefix%steamstatus'
services:
    stevotvr.steamstatus.entity:
        class: stevotvr\steamstatus\entity\steamprofile
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '%stevotvr.steamstatus.tables.steamstatus%'
    stevotvr.steamstatus.operator:
        class: stevotvr\steamstatus\operator\steamprofile
        arguments:
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.steamstatus.tables.steamstatus%'
    stevotvr.steamstatus.controller:
        class: stevotvr\steamstatus\controller\main
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@stevotvr.steamstatus.operator'
    stevotvr.steamstatus.memberlist_listener:
        class: stevotvr\steamstatus\event\memberlist_listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@stevotvr.steamstatus.operator'
            - '@template'
        tags:
            - { name: event.listener }
    stevotvr.steamstatus.ucp_listener:
        class: stevotvr\steamstatus\event\ucp_listener
        arguments:
            - '@cache'
            - '@config'
            - '@language'
            - '@request'
            - '@stevotvr.steamstatus.operator'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
    stevotvr.steamstatus.viewtopic_listener:
        class: stevotvr\steamstatus\event\viewtopic_listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@stevotvr.steamstatus.operator'
            - '@template'
        tags:
            - { name: event.listener }
