services:
    stevotvr.steamstatus.controller:
        class: stevotvr\steamstatus\controller\main
        arguments:
            - '@cache'
            - '@config'
            - '@language'
            - '@request'
    stevotvr.steamstatus.memberlist_listener:
        class: stevotvr\steamstatus\event\memberlist_listener
        arguments:
            - '@cache'
            - '@controller.helper'
            - '@language'
            - '@template'
        tags:
            - { name: event.listener }
    stevotvr.steamstatus.ucp_listener:
        class: stevotvr\steamstatus\event\ucp_listener
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
    stevotvr.steamstatus.viewtopic_listener:
        class: stevotvr\steamstatus\event\viewtopic_listener
        arguments:
            - '@cache'
            - '@controller.helper'
            - '@language'
            - '@template'
        tags:
            - { name: event.listener }
