services:
    stevotvr.steamstatus.controller:
        class: stevotvr\steamstatus\controller\main
        arguments:
            - '@config'
            - '@request'
            - '@cache'
    stevotvr.steamstatus.listener:
        class: stevotvr\steamstatus\event\main_listener
        tags:
            - { name: event.listener }
